### ISSUE TITLE
Benchmarks?

### ISSUE THREAD

**Issue by AlexDaniel** [royreznik/al-dente#1]
It'd be interesting to see how this project compares to other standard tools (find, [fd](https://github.com/sharkdp/fd?tab=readme-ov-file#benchmark), etc.).

**Comment by royreznik** [comment]
Will post benchmarks tommrow :)
As for now i have tested it againts an NTFS mount, will post those results too

**Comment by royreznik** [comment]
Added, you can see the result in the readme :)
